services:
  hyundai-server:
    # NEU: Wir laden das fertige Image aus dem Internet
    image: bausi2k/hyundai-python-server:latest
    # ALT: build: .  <-- Das brauchen wir nicht mehr!
    
    container_name: hyundai_server
    restart: unless-stopped
    ports:
      - "8444:8080"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env